function timelineEvent({
  index,
  submissionId,
  problemIndex,
  verdict,
  relativeTimeSeconds,
  sourceAvailable = false,
}) {
  return {
    index,
    submissionId,
    problemKey: "2250-" + problemIndex,
    problemIndex,
    problemName: {
      A: "Threshold Movement",
      B: "String Construction",
      C: "Rank Subsequence",
      D: "Permutation Transformation",
      E: "Skyline Queries",
    }[problemIndex],
    verdict,
    relativeTimeSeconds,
    creationTimeSeconds: 1710000000 + relativeTimeSeconds,
    programmingLanguage: "GNU C++17",
    timeConsumedMillis: 31 + (index % 5) * 17,
    memoryConsumedBytes: 1024 * (128 + index * 7),
    sourceAvailable,
  };
}

function diff({
  problemKey,
  versionIndex,
  fromSubmissionId = null,
  toSubmissionId,
  fromVerdict = "",
  toVerdict,
  fromRelativeTimeSeconds = null,
  toRelativeTimeSeconds,
  patch,
  addedLines,
  removedLines,
  changedLines,
}) {
  return {
    id: problemKey + "-" + toSubmissionId,
    problemKey,
    versionIndex,
    kind: fromSubmissionId ? "revision" : "initial",
    fromSubmissionId,
    toSubmissionId,
    fromVerdict,
    toVerdict,
    fromRelativeTimeSeconds,
    toRelativeTimeSeconds,
    programmingLanguage: "GNU C++17",
    addedLines,
    removedLines,
    changedLines,
    patch,
    coarse: false,
    sourceTruncated: false,
    patchTruncated: false,
  };
}

export function buildContestDiffMockReview(contest) {
  const sourceTimeline = [
    timelineEvent({ index: 1, submissionId: 9000001, problemIndex: "A", verdict: "WRONG_ANSWER", relativeTimeSeconds: 420, sourceAvailable: true }),
    timelineEvent({ index: 2, submissionId: 9000002, problemIndex: "A", verdict: "WRONG_ANSWER", relativeTimeSeconds: 720, sourceAvailable: true }),
    timelineEvent({ index: 3, submissionId: 9000003, problemIndex: "A", verdict: "OK", relativeTimeSeconds: 1080, sourceAvailable: true }),
    timelineEvent({ index: 4, submissionId: 9000004, problemIndex: "B", verdict: "COMPILATION_ERROR", relativeTimeSeconds: 1380 }),
    timelineEvent({ index: 5, submissionId: 9000005, problemIndex: "B", verdict: "WRONG_ANSWER", relativeTimeSeconds: 1620, sourceAvailable: true }),
    timelineEvent({ index: 6, submissionId: 9000006, problemIndex: "B", verdict: "WRONG_ANSWER", relativeTimeSeconds: 1860, sourceAvailable: true }),
    timelineEvent({ index: 7, submissionId: 9000007, problemIndex: "B", verdict: "OK", relativeTimeSeconds: 2160, sourceAvailable: true }),
    timelineEvent({ index: 8, submissionId: 9000008, problemIndex: "C", verdict: "WRONG_ANSWER", relativeTimeSeconds: 2520, sourceAvailable: true }),
    timelineEvent({ index: 9, submissionId: 9000009, problemIndex: "C", verdict: "WRONG_ANSWER", relativeTimeSeconds: 2760, sourceAvailable: true }),
    timelineEvent({ index: 10, submissionId: 9000010, problemIndex: "C", verdict: "WRONG_ANSWER", relativeTimeSeconds: 3000 }),
    timelineEvent({ index: 11, submissionId: 9000011, problemIndex: "D", verdict: "WRONG_ANSWER", relativeTimeSeconds: 3300, sourceAvailable: true }),
    timelineEvent({ index: 12, submissionId: 9000012, problemIndex: "B", verdict: "WRONG_ANSWER", relativeTimeSeconds: 3600, sourceAvailable: true }),
    timelineEvent({ index: 13, submissionId: 9000013, problemIndex: "D", verdict: "OK", relativeTimeSeconds: 3900, sourceAvailable: true }),
    timelineEvent({ index: 14, submissionId: 9000014, problemIndex: "C", verdict: "OK", relativeTimeSeconds: 4200, sourceAvailable: true }),
    timelineEvent({ index: 15, submissionId: 9000015, problemIndex: "E", verdict: "WRONG_ANSWER", relativeTimeSeconds: 4500 }),
    timelineEvent({ index: 16, submissionId: 9000016, problemIndex: "E", verdict: "WRONG_ANSWER", relativeTimeSeconds: 4740, sourceAvailable: true }),
    timelineEvent({ index: 17, submissionId: 9000017, problemIndex: "C", verdict: "OK", relativeTimeSeconds: 5100 }),
    timelineEvent({ index: 18, submissionId: 9000018, problemIndex: "D", verdict: "OK", relativeTimeSeconds: 5400 }),
    timelineEvent({ index: 19, submissionId: 9000019, problemIndex: "B", verdict: "OK", relativeTimeSeconds: 5700, sourceAvailable: true }),
    timelineEvent({ index: 20, submissionId: 9000020, problemIndex: "E", verdict: "WRONG_ANSWER", relativeTimeSeconds: 6000 }),
  ];

  const sourceDiffs = [
    diff({
      problemKey: "2250-A",
      versionIndex: 1,
      toSubmissionId: 9000001,
      toVerdict: "WRONG_ANSWER",
      toRelativeTimeSeconds: 420,
      addedLines: 6,
      removedLines: 0,
      changedLines: 0,
      patch: "@@ initial\n+#include <bits/stdc++.h>\n+using namespace std;\n+int main() {\n+  int n; cin >> n;\n+  cout << (n > 0 ? n - 1 : 0) << '\\n';\n+}",
    }),
    diff({
      problemKey: "2250-A",
      versionIndex: 2,
      fromSubmissionId: 9000001,
      toSubmissionId: 9000002,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "WRONG_ANSWER",
      fromRelativeTimeSeconds: 420,
      toRelativeTimeSeconds: 720,
      addedLines: 1,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ main()\n-  cout << (n > 0 ? n - 1 : 0) << '\\n';\n+  cout << (n >= 0 ? n - 1 : 0) << '\\n';",
    }),
    diff({
      problemKey: "2250-A",
      versionIndex: 3,
      fromSubmissionId: 9000002,
      toSubmissionId: 9000003,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "OK",
      fromRelativeTimeSeconds: 720,
      toRelativeTimeSeconds: 1080,
      addedLines: 2,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ main()\n-  cout << (n >= 0 ? n - 1 : 0) << '\\n';\n+  if (n == 0) cout << 0 << '\\n';\n+  else cout << n - 1 << '\\n';",
    }),
    diff({
      problemKey: "2250-B",
      versionIndex: 1,
      toSubmissionId: 9000005,
      toVerdict: "WRONG_ANSWER",
      toRelativeTimeSeconds: 1620,
      addedLines: 8,
      removedLines: 0,
      changedLines: 0,
      patch: "@@ initial\n+#include <bits/stdc++.h>\n+using namespace std;\n+int main() {\n+  string s; cin >> s;\n+  sort(s.begin(), s.end());\n+  cout << s << '\\n';\n+}",
    }),
    diff({
      problemKey: "2250-B",
      versionIndex: 2,
      fromSubmissionId: 9000005,
      toSubmissionId: 9000006,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "WRONG_ANSWER",
      fromRelativeTimeSeconds: 1620,
      toRelativeTimeSeconds: 1860,
      addedLines: 1,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ construction\n-  sort(s.begin(), s.end());\n+  stable_sort(s.begin(), s.end());\n   cout << s << '\\n';",
    }),
    diff({
      problemKey: "2250-B",
      versionIndex: 3,
      fromSubmissionId: 9000006,
      toSubmissionId: 9000007,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "OK",
      fromRelativeTimeSeconds: 1860,
      toRelativeTimeSeconds: 2160,
      addedLines: 3,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ construction\n-  stable_sort(s.begin(), s.end());\n+  if (s.empty()) return 0;\n+  stable_sort(s.begin(), s.end());\n+  reverse(s.begin(), s.end());\n   cout << s << '\\n';",
    }),
    diff({
      problemKey: "2250-B",
      versionIndex: 4,
      fromSubmissionId: 9000007,
      toSubmissionId: 9000012,
      fromVerdict: "OK",
      toVerdict: "WRONG_ANSWER",
      fromRelativeTimeSeconds: 2160,
      toRelativeTimeSeconds: 3600,
      addedLines: 1,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ output\n-  reverse(s.begin(), s.end());\n+  if (s.size() > 1) reverse(s.begin(), s.end());\n   cout << s << '\\n';",
    }),
    diff({
      problemKey: "2250-B",
      versionIndex: 5,
      fromSubmissionId: 9000012,
      toSubmissionId: 9000019,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "OK",
      fromRelativeTimeSeconds: 3600,
      toRelativeTimeSeconds: 5700,
      addedLines: 2,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ output\n-  if (s.size() > 1) reverse(s.begin(), s.end());\n+  const bool hasOdd = s.size() % 2 == 1;\n+  if (hasOdd) reverse(s.begin(), s.end());\n   cout << s << '\\n';",
    }),
    diff({
      problemKey: "2250-C",
      versionIndex: 1,
      toSubmissionId: 9000008,
      toVerdict: "WRONG_ANSWER",
      toRelativeTimeSeconds: 2520,
      addedLines: 7,
      removedLines: 0,
      changedLines: 0,
      patch: "@@ initial\n+vector<int> dp(n, 0);\n+for (int i = 0; i < n; ++i) {\n+  for (int j = 0; j < i; ++j) {\n+    if (a[j] < a[i])\n+      dp[i] = max(dp[i], dp[j] + 1);\n+  }\n+}\n+cout << *max_element(dp.begin(), dp.end());",
    }),
    diff({
      problemKey: "2250-C",
      versionIndex: 2,
      fromSubmissionId: 9000008,
      toSubmissionId: 9000009,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "WRONG_ANSWER",
      fromRelativeTimeSeconds: 2520,
      toRelativeTimeSeconds: 2760,
      addedLines: 2,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ transition\n-    if (a[j] < a[i])\n+    if (a[j] <= a[i])\n+      dp[i] = max(dp[i], dp[j] + 1);",
    }),
    diff({
      problemKey: "2250-C",
      versionIndex: 3,
      fromSubmissionId: 9000009,
      toSubmissionId: 9000014,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "OK",
      fromRelativeTimeSeconds: 2760,
      toRelativeTimeSeconds: 4200,
      addedLines: 3,
      removedLines: 2,
      changedLines: 2,
      patch: "@@ transition\n-    if (a[j] <= a[i])\n-      dp[i] = max(dp[i], dp[j] + 1);\n+    if (a[j] < a[i] && best[j] + 1 > best[i]) {\n+      best[i] = best[j] + 1;\n+      parent[i] = j;\n+    }",
    }),
    diff({
      problemKey: "2250-D",
      versionIndex: 1,
      toSubmissionId: 9000011,
      toVerdict: "WRONG_ANSWER",
      toRelativeTimeSeconds: 3300,
      addedLines: 8,
      removedLines: 0,
      changedLines: 0,
      patch: "@@ initial\n+vector<int> position(n);\n+for (int i = 0; i < n; ++i)\n+  position[p[i]] = i;\n+for (int value : order)\n+  answer.push_back(position[value]);\n+cout << answer.size() << '\\n';",
    }),
    diff({
      problemKey: "2250-D",
      versionIndex: 2,
      fromSubmissionId: 9000011,
      toSubmissionId: 9000013,
      fromVerdict: "WRONG_ANSWER",
      toVerdict: "OK",
      fromRelativeTimeSeconds: 3300,
      toRelativeTimeSeconds: 3900,
      addedLines: 2,
      removedLines: 1,
      changedLines: 1,
      patch: "@@ transformation\n-  position[p[value]] = i;\n+  position[p[i]] = i;\n+  inverse[position[p[i]]] = p[i];",
    }),
    diff({
      problemKey: "2250-E",
      versionIndex: 1,
      toSubmissionId: 9000016,
      toVerdict: "WRONG_ANSWER",
      toRelativeTimeSeconds: 4740,
      addedLines: 6,
      removedLines: 0,
      changedLines: 0,
      patch: "@@ initial\n+set<pair<int, int>> skyline;\n+for (auto [x, h] : queries) {\n+  skyline.insert({x, h});\n+  cout << skyline.rbegin()->second << '\\n';\n+}",
    }),
  ];

  return {
    contestId: contest?.contestId || 2250,
    contestName: contest?.contestName || "Codeforces Round 1050 (Div. 2)",
    provider: "deepseek",
    model: "deepseek-v4-flash",
    analysisMode: "source",
    sourceIncluded: true,
    sourceSubmissionCount: sourceTimeline.filter((item) => item.sourceAvailable).length,
    sourceTimeline,
    sourceDiffs,
    sourceTimelineCount: sourceTimeline.length,
    sourceDiffCount: sourceDiffs.length,
    generatedAt: new Date().toISOString(),
    summary: "演示数据：前半场在 A、B 题逐步修正，C 题连续失败后才切换到结构化建模；时间线与代码 Diff 能把这些转折点对齐。",
    strengths: [
      { title: "能把 A 题从边界错误修到 AC", evidence: "第 1、2 次提交均为 WA，第 3 次在 18 分钟通过。" },
      { title: "B 题首次 AC 后仍能根据新证据继续排查", evidence: "后续回归提交暴露了构造条件遗漏，最终在第 19 次提交修正。" },
    ],
    weaknesses: [
      { title: "C 题连续试错时没有及时重构状态", evidence: "第 8、9、10 次提交集中在同一思路，Diff 只改变局部转移条件。" },
      { title: "后半场的 E 题投入偏晚", evidence: "到 79 分钟才出现源码，早期没有先写低成本验证。" },
    ],
    timeManagement: [
      "00:07 - 00:18：A 题两次边界修正后 AC。",
      "00:23 - 00:36：B 题编译错误、两次 WA 后 AC。",
      "00:42 - 01:10：C 题连续失败，局部改动多于整体重建。",
      "01:18 之后：转向 D/E，仍有提交但缺少稳定的时间止损点。",
    ],
    problemInsights: [
      { problemKey: "2250-A", title: "边界条件", observation: "Diff 显示最终修复集中在 n == 0 的分支。", recommendation: "提交前固定检查空输入、最小值和方向切换。" },
      { problemKey: "2250-B", title: "构造细节", observation: "多次修改只围绕排序和输出顺序，说明主思路可行但不变量没有写清。", recommendation: "先写出构造后的必要性质，再决定是否反转。" },
      { problemKey: "2250-C", title: "状态设计", observation: "连续 Diff 反复改转移条件，直到补上 parent 才稳定。", recommendation: "两次 WA 后暂停局部修补，重新确认排序结构与状态含义。" },
      { problemKey: "2250-D", title: "可争取分数", observation: "第一次提交是错误的下标映射，随后一次修正通过。", recommendation: "保留至少 30 分钟给尚未尝试的中档题。" },
    ],
    actions: [
      { priority: "high", title: "两次 WA 后强制重新建模", reason: "减少连续局部改动，把 Diff 暴露出的重复模式转成检查清单。", problemKeys: ["2250-B", "2250-C"] },
      { priority: "high", title: "前 45 分钟完成 A/B 取舍", reason: "若 B 仍未稳定，先阅读 C/D 并留下低成本尝试。", problemKeys: ["2250-B", "2250-C", "2250-D"] },
      { priority: "medium", title: "提交前覆盖最小样例", reason: "A、B 的有效修复都落在边界或构造顺序上。", problemKeys: ["2250-A", "2250-B"] },
    ],
  };
}
